# ========================LICENSE_START=================================
# O-RAN-SC
# %%
# Copyright (C) 2019 AT&T Intellectual Property and Nokia
# %%
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================LICENSE_END===================================
swagger : '2.0'
info :
  description : REST API specification for RIC ANR closed xAPP
  version     : 0.0.2
  title       : RIC ANR
  license:
    name : Nokia Closed App
    url  : 'http://www.nokia.com'
host     : anr-service
basePath : /ric/v1
schemes :
  - https
  - http
paths :
  /health/alive :
    get :
      summary     : Health check of ANR - Liveness probe
      tags        :
        - health
      operationId : getHealthAlive
      responses   :
        '200' :
          description : Status of ANR xApp is ok
  /health/ready :
    get :
      summary     : Health check of ANR - Readiness probe
      tags        :
        - health
      operationId : getHealthReady
      responses   :
        '200':
          description : Status of ANR xApp is ok
  /ncrt/cell :
    parameters :
      - $ref : '#/parameters/ggnbId'
      - $ref : '#/parameters/startIndex'
      - $ref : '#/parameters/limit'
    get :
      summary     : Returns NCRT Table for all gnodeBs or based on query string
      tags        :
        - ncrt
      operationId : getNcrtInfo
      produces  :
        - application/json
      responses :
        '200' :
          description : successful operation
          schema      :
            $ref : '#/definitions/NCRTTable'
        '400' :
          description : Non-existant identifier {ggnbId | neighborCellIdentifier | start Index} in request
  /ncrt/cell/{cellIdentifier} :
    parameters :
      - $ref : '#/parameters/cellIdentifier'
      - $ref : '#/parameters/startIndex'
      - $ref : '#/parameters/limit'
      - $ref : '#/parameters/neighborCellIdentifierNrpci'
      - $ref : '#/parameters/neighborCellIdentifierNrcgi'
    get :
      summary     : Returns NCRT Table for a Source Cell (NR CGI) and optionally a neighbor cell based on query string
      tags        :
        - ncrt
      operationId : getCellNcrtInfo
      produces  :
        - application/json
      responses :
        '200' :
          description : successful operation
          schema      :
            $ref : '#/definitions/NCRTTable'
        '400' :
          description : Non-existant identifier {cellIdentifier | neighborCellIdentifierNrpci | neighborCellIdentifierNrcgi} in request
    put :
      summary     : Modify NCRT relation based on Source Cell NR CGI and Target Cell NR PCI / NR CGI
      tags        :
        - ncrt
      operationId : modifyNCRT
      consumes   :
        - application/json
      produces   :
        - application/json
      parameters :
        - name        : NCRTModificationParameters
          in          : body
          description : Parameters to modify NCRT entry
          required    : true
          schema :
            $ref : '#/definitions/NCRTModTable'
      responses :
        '200' :
          description : Successfully modified NCRT relation
        '400' :
          description : Modification failed.
                        { Identifier neighborCellIdentifierNrpci / neighborCellIdentifierNrcgi not provided |
                          Non-existant identifier {cellIdentifier | neighborCellIdentifierNrpci | neighborCellIdentifierNrcgi} in request |
                          Invalid data in body
                        }
    delete :
      summary     : Delete NCRT row based on Source Cell NR CGI and Target Cell NR PCI / NR CGI
      tags        :
        - ncrt
      operationId : deleteNcrt
      parameters :
        - name        : NCRTDeletionParameters
          in          : body
          description : Parameters to modify NCRT entry
          required    : true
          schema      :
            $ref : '#/definitions/NCRTDelTable'
      responses :
        '204' :
          description : Successfully deleted NCRT relation
        '400' :
          description : Deletion failed.
                        { Identifier neighborCellIdentifierNrpci / neighborCellIdentifierNrcgi not provided |
                          Non-existant identifier {cellIdentifier | neighborCellIdentifierNrpci | neighborCellIdentifierNrcgi} in request
                        }
parameters :
  ggnbId :
    type        : string
    name        : ggnbId
    description : Global gNodeB Identifier
    in          : query
  startIndex :
    type        : string
    name        : startIndex
    description : Pagination Index
    in          : query
  limit :
    type        : integer
    name        : limit
    description : Limit of results that client can handle
    in          : query
  cellIdentifier :
    type        : string
    name        : cellIdentifier
    description : Source Cell Identifier (NR CGI)
    in          : path
    required    : true
  neighborCellIdentifierNrpci :
    type        : string
    name        : neighborCellIdentifierNrpci
    description : Neighbor Cell Identifier (NR PCI)
    in          : query
  neighborCellIdentifierNrcgi :
    type        : string
    name        : neighborCellIdentifierNrcgi
    description : Neigbhor Cell Identifier (NR CGI)
    in          : query
definitions :
  NCRTTable :
    type       : object
    properties :
      ncrtRelations :
        type   : array
        items  :
          $ref : '#/definitions/NCRTRow'
      startIndex :
        type        : string
        description : Index to use in REST API to process multipage results
        example     : 1245A:6740B
  NCRTModTable :
    type   : array
    items  :
      $ref : '#/definitions/NCRTModification'
  NCRTDelTable :
    type   : array
    items  :
      $ref : '#/definitions/NCRTDeletion'
  NCRTRow :
    type  : object
    required :
      - cellIdentifierNrcgi
      - neighborCellIdentifierNrpci
      - neighborCellIdentifierNrcgi
      - flagNoHo
      - flagNoXn
      - flagNoRemove
    properties :
      cellIdentifierNrcgi :
        type        : string
        description : Source / Serving Cell Identifier (NR CGI)
        example     : E12345
      neighborCellIdentifierNrpci :
        type        : string
        description : Neighbor Cell Identifier (NR PCI)
        example     : E12345
      neighborCellIdentifierNrcgi :
        type        : string
        description : Neighbor Cell Identifier (NR CGI)
        example     : E12345
      flagNoHo :
        type        : boolean
        description : Flag for HANDOVER NOT ALLOWED
        example     : True
      flagNoXn :
        type        : boolean
        description : Flag for Xn CONNECTION NOT ALLOWED
        example     : True
      flagNoRemove :
        type        : boolean
        description : Flag for DELETION NOT ALLOWED
        example     : True
  NCRTModification :
    type      : object
    required  :
      - neighbourCellIdentifierType
      - action
    properties :
      neighbourCellIdentifierType :
        type        : string
        description : Neighbor Cell Identifier Type
        enum :
          - nrpci
          - nrcgi
      action :
        type        : string
        description : Modification action to be performed
        enum :
          - nrpciToNrcgiMapping
          - flagUpdates
          - nrcgiMappingAndFlagUpdates
      neighborCellIdentifierNrpci :
        type        : string
        description : Neighbor Cell Identifier (NR PCI)
        example     : E12345
      neighborCellIdentifierNrcgi :
        type        : string
        description : Neighbor Cell Identifier (NR CGI)
        example     : E12345
      flagNoHo :
        type        : boolean
        description : Flag for HANDOVER NOT ALLOWED
        example     : True
      flagNoXn :
        type        : boolean
        description : Flag for Xn CONNECTION NOT ALLOWED
        example     : True
      flagNoRemove :
        type        : boolean
        description : Flag for DELETION NOT ALLOWED
        example     : True
  NCRTDeletion :
    type      : object
    required  :
      - idType
    properties :
      idType :
        type        : string
        description : Modification action to be performed
        enum :
          - nrpci
          - nrcgi
      neighborCellIdentifierNrpci :
        type        : string
        description : Neighbor Cell Identifier (NR PCI)
        example     : E12345
      neighborCellIdentifierNrcgi :
        type        : string
        description : Neighbor Cell Identifier (NR PCI)
        example     : E12345
